### ISSUE TITLE
How to test demo with IP camera (RTSP)

### ISSUE THREAD

**Issue by RamGitHub83** [aws-samples/amazon-rekognition-ppe#45]
Hi Team,

Thanks for sharing...
Please help me in below 2 points.
1. As per guidelines I can able to run demo from local machine, I placed some breakpoints but while running demo break points are not hit - directly executed. how can I run this demo with breakpoints to execute step by step in IDE: PyCham.

2. Demo application is working with Web Camera, how can I test with IP Camera in this demo. where I need to made required changes.

Thanks
Ramachandra Reddy

**Comment by ctd** [comment]
1. Which code are you running from the repository in PyCharm? The in-browser demo does not use Python, so PyCharm mightn't be the best tool for this. You'd be best to consult the manual/software vendor for support.

2. As I mentioned in #44, the demo is built to make use of browser APIs for working with webcams. It might not be practical to try and retrofit IP camera support onto the demo, since this isn't a common browser use-case and there aren't first-party APIs from browsers available to do it.

You might want to take a look at https://github.com/aws-samples/amazon-rekognition-video-analyzer as an example of using Rekognition with an IP camera.

**Comment by RamGitHub83** [comment]
Hi ctd,

Please suggest best tool for this demo to run locally with breakpoint execution.

Thanks in advance.

**Comment by ctd** [comment]
I'd suggest using the web developer tools included with your web browser. I know the web developer tools included with Firefox and Chrome are quite good and can be used to add breakpoints, inspect execution state, etc..

**Comment by ctd** [comment]
I'm closing this issue as it's been inactive for several days. If you require any further assistance using the demo please post a comment to reopen it.
